services:
  videostreamsrv:
    build: .
    container_name: video-stream
    environment:
      PORT: 3000
      VIDEO_LIBRARY_PATH: /library
      CACHE_PATH: /cache
      THUMBNAIL_TIMESTAMP: 15
      HLS_ENABLED: "true"
    volumes:
      - ./videos:/library:ro
      - ./cache:/cache
    networks:
      - ptfin-backend

networks:
  ptfin-backend:
    external: true
